In [1]:
import math
import numpy as np

def gauss(x, y, sigma):
    """
    Calcul de la valeur de la fonction gaussienne en (x, y).
    """
    part1 = 1 / (2 * math.pi * pow(sigma, 2))
    part2 = -(x * x + y * y) / (2 * pow(sigma, 2))
    return part1 * math.exp(part2)

def generate_gauss_mask(sigma=1.4, vois_mat=3):
    """
    Génère une matrice de convolution gaussienne de taille `vois_mat x vois_mat`.
    """
    vois = int(vois_mat / 2)
    mask = np.zeros((vois_mat, vois_mat))  # Création de la matrice du masque

    for i in range(-vois, vois + 1):
        for j in range(-vois, vois + 1):
            mask[i + vois, j + vois] = gauss(i, j, sigma)

    # Normaliser le masque pour que la somme des valeurs soit égale à 1
    mask = mask / np.sum(mask)
    
    return mask

def apply_convolution(image, mask):
    """
    Applique une convolution 2D avec un masque sur une image.
    """
    image_height, image_width = image.shape
    mask_height, mask_width = mask.shape
    output_image = np.zeros_like(image)

    # Calcul des bords à appliquer à l'image
    pad_height = mask_height // 2
    pad_width = mask_width // 2
    
    # Appliquer le masque à chaque pixel de l'image
    for i in range(pad_height, image_height - pad_height):
        for j in range(pad_width, image_width - pad_width):
            region = image[i - pad_height:i + pad_height + 1, j - pad_width:j + pad_width + 1]
            output_image[i, j] = np.sum(region * mask)

    return output_image

# Exemple d'utilisation :
sigma = 1.4
mask_size = 3
mask = generate_gauss_mask(sigma, mask_size)

# Exemple d'image (matrice aléatoire 5x5 pour démonstration)
image = np.random.rand(5, 5)

# Appliquer la convolution
output_image = apply_convolution(image, mask)

print("Masque Gaussien :\n", mask)
print("Image d'entrée :\n", image)
print("Image après convolution :\n", output_image)


Masque Gaussien :
 [[0.09235312 0.11919032 0.09235312]
 [0.11919032 0.15382623 0.11919032]
 [0.09235312 0.11919032 0.09235312]]
Image d'entrée :
 [[0.86841562 0.79680616 0.85529491 0.96945075 0.79388537]
 [0.23009915 0.55082367 0.37662976 0.10676799 0.20293945]
 [0.91813917 0.7212647  0.8372155  0.44186815 0.19574214]
 [0.585249   0.96796729 0.07980854 0.37882336 0.2499805 ]
 [0.23557218 0.76039346 0.07232339 0.68727335 0.83223718]]
Image après convolution :
 [[0.         0.         0.         0.         0.        ]
 [0.         0.65928923 0.60858324 0.50142212 0.        ]
 [0.         0.61864935 0.50693387 0.33294933 0.        ]
 [0.         0.59531409 0.52232479 0.41109922 0.        ]
 [0.         0.         0.         0.         0.        ]]


In [ ]:
import math
import numpy as np
import cv2

def gauss(x, y, sigma):
    """
    Calcul de la valeur de la fonction gaussienne en (x, y).
    """
    part1 = 1 / (2 * math.pi * pow(sigma, 2))
    part2 = -(x * x + y * y) / (2 * pow(sigma, 2))
    return part1 * math.exp(part2)

def generate_gauss_mask(sigma=1.4, vois_mat=3):
    """
    Génère une matrice de convolution gaussienne de taille `vois_mat x vois_mat`.
    """
    vois = int(vois_mat / 2)
    mask = np.zeros((vois_mat, vois_mat))

    for i in range(-vois, vois + 1):
        for j in range(-vois, vois + 1):
            mask[i + vois, j + vois] = gauss(i, j, sigma)

    mask = mask / np.sum(mask)
    
    return mask

def apply_convolution(image, mask):
    """
    Applique une convolution 2D avec un masque sur une image.
    """
    image_height, image_width = image.shape
    mask_height, mask_width = mask.shape
    output_image = np.zeros_like(image)

    pad_height = mask_height // 2
    pad_width = mask_width // 2
    
    for i in range(pad_height, image_height - pad_height):
        for j in range(pad_width, image_width - pad_width):
            region = image[i - pad_height:i + pad_height + 1, j - pad_width:j + pad_width + 1]
            output_image[i, j] = np.sum(region * mask)

    return output_image

def main(image_path, sigma=1.4, mask_size=3):
    """
    Fonction principale pour charger l'image, appliquer la convolution gaussienne.
    """
    image = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)

    mask = generate_gauss_mask(sigma, mask_size)

    output_image = apply_convolution(image, mask)

    # Affichage des images avec OpenCV
    cv2.imshow('Image Originale', image)
    cv2.imshow('Image après Convolution', output_image)

    # Attente de la touche 'q' pour fermer les fenêtres
    cv2.waitKey(0)
    cv2.destroyAllWindows()

image_path = 'nSpeyoLESmG6w-u2amRdww.jpg'  # Remplacez par le chemin de votre image
main(image_path, sigma=1.4, mask_size=3)


# TP 6

In [1]:
import cv2 
import numpy as np 
 
sizeDelate = 1 
sizeErode = 1 
 
cv2.namedWindow("Erosion") 
cv2.namedWindow("Dilatation") 
img = cv2.imread("nSpeyoLESmG6w-u2amRdww.jpg", cv2.IMREAD_GRAYSCALE) 
cv2.threshold(img, 130, 255, 0, img) 
 
def delate_func(): 
    # kernel = np.ones((sizeDelate, sizeDelate), np.uint8) 
    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (sizeDelate * 2 + 1, sizeDelate * 2 + 1)) 
    img_delate = cv2.dilate(img, kernel, iterations=1) 
    # img_delate = cv2.morphologyEx(img, cv2.MORPH_OPEN, kernel) 
    cv2.imshow("Dilatation", img_delate) 
 
def erode_func(): 
    # kernel = np.ones((sizeErode, sizeErode), np.uint8) 
    kernel = cv2.getStructuringElement(cv2.MORPH_CROSS, (sizeErode * 2 + 1, sizeErode * 2 + 1)) 
    img_erode = cv2.erode(img, kernel, iterations=1) 
    cv2.imshow("Erosion", img_erode) 
def changeEsize(x): 
    global sizeErode 
    sizeErode = x 
    erode_func() 
 
def changeDsize(x): 
    global sizeDelate 
    sizeDelate = x 
    delate_func() 
 
cv2.createTrackbar("Size Erode", "Erosion", 0, 21, changeEsize) 
cv2.createTrackbar("Size Delete", "Dilatation", 0, 21, changeDsize) 
erode_func() 
delate_func() 
 
cv2.imshow("image source", img) 
cv2.waitKey(0) 
cv2.destroyAllWindows()

In [ ]:
import cv2 as cv
import numpy as np
import matplotlib.pyplot as plt

img = cv.imread('C:/Users/PC/Desktop/COURS/VISION/odachi.jpg', cv.IMREAD_GRAYSCALE)

assert img is not None, print("Error loading image")

cv.threshold(img, 128, 255, 0, img)


erode_size = 1
def erode_func():
    size = erode_size*2 + 1
    kernel = cv.getStructuringElement(cv.MORPH_CROSS, (size, size))
    img_eroded = cv.erode(img, kernel, iterations=1)
    cv.imshow('erode', img_eroded)
def chenge_erode_size(x:float):
    global erode_size
    erode_size = x
    erode_func()
    print("erode_size: ", erode_size)
cv.namedWindow("erode")
erode_func()

dilate_size = 1
def dilate_func():
    size = dilate_size*2 + 1
    kernel = cv.getStructuringElement(cv.MORPH_CROSS, (size, size))
    img_dilated = cv.dilate(img, kernel, iterations=1)
    cv.imshow('dilate', img_dilated)
def chenge_dilate_size(x:float):
    global dilate_size
    dilate_size = x
    dilate_func()
    print("dilate_size: ", erode_size)
cv.namedWindow("dilate")
dilate_func()

morph_size = 1
def morph_func():
    size = morph_size*2 + 1
    kernel = cv.getStructuringElement(cv.MORPH_CROSS, (size, size))
    img_morphd = cv.morphologyEx(img, cv.MORPH_OPEN, kernel, iterations=1)
    cv.imshow('morph', img_morphd)
def chenge_morph_size(x:float):
    global morph_size
    morph_size = x
    morph_func()
    print("morph_size: ", erode_size)
cv.namedWindow("morph")
morph_func()

cv.createTrackbar("sizeErode", "erode", 0, 11, chenge_erode_size)
cv.createTrackbar("sizeDilate", "dilate", 0, 11, chenge_dilate_size)
cv.createTrackbar("sizeMorph", "morph", 0, 11, chenge_morph_size)

size = erode_size*2 + 1
kernel = cv.getStructuringElement(cv.MORPH_CROSS, (size, size))
imgRes = img.copy()
cv.morphologyEx(img, 2, kernel, imgRes)

# cv.imshow('test', img)
cv.imshow('test3', imgRes)



cv.waitKey(0)
cv.destroyAllWindows()

In [ ]:
import cv2 as cv
import numpy as np
import matplotlib.pyplot as plt

img = cv.imread('nSpeyoLESmG6w-u2amRdww.jpg', cv.IMREAD_GRAYSCALE)

assert img is not None, print("Error loading image")

cv.threshold(img, 128, 255, 0, img)


erode_size = 1
def erode_func():
    size = erode_size*2 + 1
    kernel = cv.getStructuringElement(cv.MORPH_CROSS, (size, size))
    img_eroded = cv.erode(img, kernel, iterations=1)
    cv.imshow('erode', img_eroded)
def chenge_erode_size(x:float):
    global erode_size
    erode_size = x
    erode_func()
    print("erode_size: ", erode_size)
cv.namedWindow("erode")
erode_func()

dilate_size = 1
def dilate_func():
    size = dilate_size*2 + 1
    kernel = cv.getStructuringElement(cv.MORPH_CROSS, (size, size))
    img_dilated = cv.dilate(img, kernel, iterations=1)
    cv.imshow('dilate', img_dilated)
def chenge_dilate_size(x:float):
    global dilate_size
    dilate_size = x
    dilate_func()
    print("dilate_size: ", erode_size)
cv.namedWindow("dilate")
dilate_func()

morph_size = 1
def morph_func():
    size = morph_size*2 + 1
    kernel = cv.getStructuringElement(cv.MORPH_CROSS, (size, size))
    img_morphd = cv.morphologyEx(img, cv.MORPH_OPEN, kernel, iterations=1)
    cv.imshow('morph', img_morphd)
def chenge_morph_size(x:float):
    global morph_size
    morph_size = x
    morph_func()
    print("morph_size: ", erode_size)
cv.namedWindow("morph")
morph_func()

cv.createTrackbar("sizeErode", "erode", 0, 11, chenge_erode_size)
cv.createTrackbar("sizeDilate", "dilate", 0, 11, chenge_dilate_size)
cv.createTrackbar("sizeMorph", "morph", 0, 11, chenge_morph_size)

size = erode_size*2 + 1
kernel = cv.getStructuringElement(cv.MORPH_CROSS, (size, size))
imgRes = img.copy()
cv.morphologyEx(img, 2, kernel, imgRes)

# cv.imshow('test', img)
cv.imshow('test3', imgRes)



cv.waitKey(0)
cv.destroyAllWindows()